### ISSUE TITLE
Тесты на поиск пишутся в трёх вариантах

### ISSUE THREAD

**Issue by coursar** [banch0/home#5]
https://github.com/banch0/home/blob/50d01830412610e36dbe3510bdd3120936c207d7/example_main_test.go#L72-L75

1. Ничего не найдено
2. Найдено ровно 1
3. Найдено несколько

Мы же обсуждали это всё на лекции

**Comment by banch0** [comment]
Для третьего пункта, как вернуть несколько если условия задания было в пределах стоимости не ниже и не выше, от куда взять предел?

**Comment by coursar** [comment]
Разве не может поиск вернуть несколько домов? Только один или ничего?
