### ISSUE TITLE
Ещё раз: задача научиться пользоваться анонимными функциями и передавать их

### ISSUE THREAD

**Issue by coursar** [banch0/home#7]
https://github.com/banch0/home/blob/862b5008f72281c526bfb3a5f6971c24feae8623/main.go#L89-L144

По вашему коду не видно, что вы научились

Должна быть одна фукнция `SortBy`, остальные используют её. Больше повторять не буду - если не сделаете, будет незачёт.

**Comment by banch0** [comment]
Значит пакет sort нельзя использовать? Или можно?

**Comment by coursar** [comment]
Можно, но только в одной функции
